../data/colo_utah_all.rda ../data/utah_utah.rda : build-colo-and-utah.R ../../../pedalfast-data-new/PCHdata/UTforanalysis.csv ../../../pedalfast-data-new/CHCOdata/COforanalysis.csv
	R CMD BATCH --vanilla $<
